
spring:
  application:
    name: elearner-ws
  h2:
    console:
      enabled: true
    settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:elearnerdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

server:
  port: 8070